version: '3.8'

services:
  django:
    build: .
    command: gunicorn notemanagement.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.postgres.env
      - ./.envs/.django.env

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres.env

volumes:
  postgres_data: {}
  postgres_data_backups: {}
